### ISSUE TITLE
code tags

### ISSUE THREAD

**Issue by Goheeca** [archimag/cliki2#11]
It'd be great if the inner converter (from &lt;code lang="common lisp"&gt; to some &lt;div&gt; structure) would work as if the code tag had in a style attribute "white-space: pre;", simply makes code tags work like pre tags

**Comment by vsedach** [comment]
I agree. I remember trying to do that and there was some problem. The nesting of different tags got very ugly and I had to make a lot of hacks to make it work properly. For example the function generate-html-from-markup in markup.lisp is very ugly and brittle. If you would like to try to get it working, the function markup-code in markup.lisp is the place, but it's a good idea to test a lot of pages from cliki.net because that's where I found the problems.

**Comment by vsedach** [comment]
Goheeca made this change in https://gitlab.common-lisp.net/vsedach/cliki2-style/commit/285b106d192ed37d0318a734b617201ab5acf8f3
